name: minder
description: " A memory support app for short-term memory loss individuals, using video recording and 
               transcription for personalized memory aids. Reminds and revisit 
               crucial moments effortlessly."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2 
  permission_handler: ^11.3.0 
  path: ^1.8.0
  
  universal_io: ^2.2.2
  speech_to_text: ^6.6.0
  audioplayers: ^5.2.1 
  google_ml_kit: ^0.16.3
  local_auth: ^2.2.0   
  image_picker: ^1.0.7 # Check for the latest version 
  amplify_flutter: ^0.4.2
  amplify_storage_s3: ^0.4.2
  amplify_auth_cognito: ^0.4.2
  timezone: ^0.8.0 
  flutter_sound: ^9.2.13  
  flutter_ffmpeg: ^0.4.1  
  video_player: ^2.8.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.5 
  tutorial_coach_mark: ^1.2.11
  add_2_calendar: ^3.0.1  
  flutter_local_notifications: ^9.1.4 # Check for the latest version
  intl: ^0.17.0 # For date formatting
  sqflite: ^2.0.0+3
  sqlite_viewer: ^1.0.5
  uuid: ^3.0.7
  flutter_config: ^2.0.2
  http: ^1.2.1
  mockito: ^5.0.15
  dotenv: ^4.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
    

  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/minder_logo.png
    - asset/images/clock.jpg
    - asset/images/Caregiver_loginimg.png
    - asset/images/profile-grandmother.jpg   
    - asset/images/guideTour.jpg
    - asset/images/support.jpg
    - asset/images/x.jpg
    - asset/images/speech-recognition.jpg  
    - asset/images/caregiver_signup.jpg  
    - asset/images/caregiver_login.jpg
    - asset/images/profile.jpg
    - asset/sound/piano-logo-108963.mp3
    - asset/images/minderlogo2.png
    - asset/images/sound-blue-effect.png
    - asset/images/white-background_sound.jpg
    - asset/images/signupcomplete.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
